/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"

float *
sum_1_svc(inputs *argp, struct svc_req *rqstp)
{
    static float result;
    result = argp->i + argp->j;
    return &result;
}

float *
res_1_svc(inputs *argp, struct svc_req *rqstp)
{
    static float result;
    result = argp->i - argp->j;
    return &result;
}

float *
mul_1_svc(inputs *argp, struct svc_req *rqstp)
{
    static float result;
    result = argp->i * argp->j;
    return &result;
}

float *
div_1_svc(inputs *argp, struct svc_req *rqstp)
{
    static float result;
    if (argp->j == 0) {
        result = 0; // evitar división por cero
    } else {
        result = argp->i / argp->j;
    }
    return &result;
}
