/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	float i;
	float j;
	char operator;
};
typedef struct inputs inputs;

#define CALCU_PROG 0x2fffffff
#define CALCU_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  float * sum_1(inputs *, CLIENT *);
extern  float * sum_1_svc(inputs *, struct svc_req *);
#define RES 2
extern  float * res_1(inputs *, CLIENT *);
extern  float * res_1_svc(inputs *, struct svc_req *);
#define DIV 3
extern  float * div_1(inputs *, CLIENT *);
extern  float * div_1_svc(inputs *, struct svc_req *);
#define MUL 4
extern  float * mul_1(inputs *, CLIENT *);
extern  float * mul_1_svc(inputs *, struct svc_req *);
extern int calcu_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  float * sum_1();
extern  float * sum_1_svc();
#define RES 2
extern  float * res_1();
extern  float * res_1_svc();
#define DIV 3
extern  float * div_1();
extern  float * div_1_svc();
#define MUL 4
extern  float * mul_1();
extern  float * mul_1_svc();
extern int calcu_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
