/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"


char *host;

void
calcu_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	inputs  sum_1_arg;
	float  *result_2;
	inputs  res_1_arg;
	float  *result_3;
	inputs  div_1_arg;
	float  *result_4;
	inputs  mul_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCU_PROG, CALCU_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sum_1(&sum_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = res_1(&res_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = div_1(&div_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = mul_1(&mul_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

CLIENT *Conectar_servidor() {
    CLIENT *clnt;
    clnt = clnt_create(host, CALCU_PROG, CALCU_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
    return clnt;
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("Uso: %s <host>\n", argv[0]);
        exit(1);
    }

    host = argv[1];
    CLIENT *clnt = Conectar_servidor();
    inputs datos;
    float *result;

    printf("Introduce el primer número: ");
    scanf("%f", &datos.i);
    printf("Introduce el operador (+, -, *, /): ");
    scanf(" %c", &datos.operator);
    printf("Introduce el segundo número: ");
    scanf("%f", &datos.j);

    switch (datos.operator) {
        case '+':
            result = sum_1(&datos, clnt);
            break;
        case '-':
            result = res_1(&datos, clnt);
            break;
        case '*':
            result = mul_1(&datos, clnt);
            break;
        case '/':
            result = div_1(&datos, clnt);
            break;
        default:
            printf("Operador no válido.\n");
            clnt_destroy(clnt);
            exit(1);
    }

    if (result == (float *)NULL) {
        clnt_perror(clnt, "Error en llamada RPC");
        exit(1);
    }

    printf("Resultado: %.2f %c %.2f = %.2f\n", datos.i, datos.operator, datos.j, *result);
    clnt_destroy(clnt);
    return 0;
}
